In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("../data/Healthcare_dataset.xlsx")

df.head()

,Patient ID,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Test Results,Medication,Severity,Dosage,Treatment Outcome
0,ID0001,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Normal,Imatinib,Moderate,400 mg,Improving
1,ID0002,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Inconclusive,Liraglutide,Mild,0.6 mg,Stable
2,ID0003,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Normal,Orlistat,Severe,120 mg,Critical
3,ID0004,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Abnormal,Glipizide,Moderate,5 mg,Improving
4,ID0005,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Abnormal,Imatinib,Moderate,400 mg,Critical

In [3]:
df.shape

(999, 19)

In [4]:
df.describe()

,Age,Date of Admission,Billing Amount,Room Number,Discharge Date
count,999.000000,999,999.000000,999.000000,999
mean,50.972973,2021-10-12 01:30:48.648648704,25099.622670,295.170170,2021-10-27 17:46:39.999999744
min,18.000000,2019-05-10 00:00:00,-1018.245371,101.000000,2019-05-20 00:00:00
25%,34.000000,2020-06-16 00:00:00,12049.207281,192.500000,2020-06-27 00:00:00
50%,51.000000,2021-09-16 00:00:00,24690.222177,295.000000,2021-10-10 00:00:00
75%,67.000000,2023-01-15 12:00:00,37777.215683,396.500000,2023-01-28 12:00:00
max,85.000000,2024-05-05 00:00:00,51587.936817,500.000000,2024-05-24 00:00:00
std,19.687241,NaN,14460.387378,116.942534,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Patient ID          999 non-null    object
 1   Name                999 non-null    object
 2   Age                 999 non-null    int64
 3   Gender              999 non-null    object
 4   Blood Type          999 non-null    object
 5   Medical Condition   999 non-null    object
 6   Date of Admission   999 non-null    datetime64[ns]
 7   Doctor              999 non-null    object
 8   Hospital            999 non-null    object
 9   Insurance Provider  999 non-null    object
 10  Billing Amount      999 non-null    float64
 11  Room Number         999 non-null    int64
 12  Admission Type      999 non-null    object
 13  Discharge Date      999 non-null    datetime64[ns]
 14  Test Results        999 non-null    object
 15  Medication          999 non-null    object
 16  Severity            999 non-null    object
 17  Dosage              999 non-null    object
 18  Treatment Outcome   999 non-null    object
dtypes: datetime64[ns](2), float64(1), int64(2), object(14)
memory usage: 148.4+ KB

In [6]:
df.isnull().sum()

Patient ID            0
Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Test Results          0
Medication            0
Severity              0
Dosage                0
Treatment Outcome     0
dtype: int64

In [7]:
df = df.drop_duplicates()

In [8]:
df.shape

(999, 19)

In [9]:
df["Date of Admission"] = pd.to_datetime(df["Date of Admission"])
df["Discharge Date"] = pd.to_datetime(df["Discharge Date"])

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Patient ID          999 non-null    object
 1   Name                999 non-null    object
 2   Age                 999 non-null    int64
 3   Gender              999 non-null    object
 4   Blood Type          999 non-null    object
 5   Medical Condition   999 non-null    object
 6   Date of Admission   999 non-null    datetime64[ns]
 7   Doctor              999 non-null    object
 8   Hospital            999 non-null    object
 9   Insurance Provider  999 non-null    object
 10  Billing Amount      999 non-null    float64
 11  Room Number         999 non-null    int64
 12  Admission Type      999 non-null    object
 13  Discharge Date      999 non-null    datetime64[ns]
 14  Test Results        999 non-null    object
 15  Medication          999 non-null    object
 16  Severity            999 non-null    object
 17  Dosage              999 non-null    object
 18  Treatment Outcome   999 non-null    object
dtypes: datetime64[ns](2), float64(1), int64(2), object(14)
memory usage: 148.4+ KB

In [11]:
df["length_of_stay"] = (
    df["Discharge Date"] - df["Date of Admission"]
).dt.days

In [12]:
df[["Date of Admission","Discharge Date","length_of_stay"]].head()

  Date of Admission Discharge Date  length_of_stay
0        2024-01-31     2024-02-02               2
1        2019-08-20     2019-08-26               6
2        2022-09-22     2022-10-07              15
3        2020-11-18     2020-12-18              30
4        2022-09-19     2022-10-09              20

In [13]:
df.to_csv("../data/cleaned_healthcare_data.csv", index=False)

In [14]:
df = df.drop(columns=[
"Patient ID",
"Name",
"Doctor",
"Hospital",
"Room Number"
])

In [15]:
df.columns

Index(['Age', 'Gender', 'Blood Type', 'Medical Condition', 'Date of Admission',
       'Insurance Provider', 'Billing Amount', 'Admission Type',
       'Discharge Date', 'Test Results', 'Medication', 'Severity', 'Dosage',
       'Treatment Outcome', 'length_of_stay'],
      dtype='object')

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
encoder = LabelEncoder()

In [18]:
categorical_cols = [
"Gender",
"Blood Type",
"Medical Condition",
"Insurance Provider",
"Admission Type",
"Test Results",
"Medication",
"Severity",
"Dosage",
"Treatment Outcome"
]

for col in categorical_cols:
    df[col] = encoder.fit_transform(df[col])

In [19]:
df.head()

,Age,Gender,Blood Type,Medical Condition,Date of Admission,Insurance Provider,Billing Amount,Admission Type,Discharge Date,Test Results,Medication,Severity,Dosage,Treatment Outcome,length_of_stay
0,30,1,5,2,2024-01-31,1,18856.281306,2,2024-02-02,2,5,1,9,1,2
1,62,1,0,5,2019-08-20,3,33643.327287,1,2019-08-26,1,7,0,0,3,6
2,76,0,1,5,2022-09-22,0,27955.096079,1,2022-10-07,2,14,2,3,0,15
3,28,0,6,3,2020-11-18,3,37909.782410,0,2020-12-18,0,3,1,10,1,30
4,43,0,2,2,2022-09-19,0,14238.317814,2,2022-10-09,0,5,1,9,0,20

In [20]:
df = df.drop(columns=[
"Date of Admission",
"Discharge Date"
])

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 999 non-null    int64
 1   Gender              999 non-null    int64
 2   Blood Type          999 non-null    int64
 3   Medical Condition   999 non-null    int64
 4   Insurance Provider  999 non-null    int64
 5   Billing Amount      999 non-null    float64
 6   Admission Type      999 non-null    int64
 7   Test Results        999 non-null    int64
 8   Medication          999 non-null    int64
 9   Severity            999 non-null    int64
 10  Dosage              999 non-null    int64
 11  Treatment Outcome   999 non-null    int64
 12  length_of_stay      999 non-null    int64
dtypes: float64(1), int64(12)
memory usage: 101.6 KB

In [22]:
df.to_csv("../data/ml_ready_data.csv", index=False)